# Generated by Django 3.0.3 on 2020-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tweet', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
